<?php

namespace OC\CoursBundle\Repository;

/**
 * ElevePresenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElevePresenceRepository extends \Doctrine\ORM\EntityRepository
{
}
