<?php

namespace OC\CoursBundle\Repository;

/**
 * SemainesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemainesRepository extends \Doctrine\ORM\EntityRepository
{
}
