<?php

namespace OC\EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByType($key) {
      $query = $this->getEntityManager()
                        ->createQuery("
	            SELECT p FROM OCEvenementBundle:Evenement p
	            WHERE p.type LIKE :key "
                        );
        $query->setParameter('key', $key.'%');
        return $query->getResult();

    }
    
    public function estParticipant($evenement,$user){
        $participants=$evenement->getParticipants();
        foreach ($participants as $participant){
            if ($user->getId()==$participant->getId()){
                return true;
            }
        }
        return false;
    }
    
    public function estNonParticipant($evenement, $user){
                $nonparticipants=$evenement->getNonParticipants();
        foreach ($nonparticipants as $participant){
            if ($user->getId()==$participant->getId()){
                return true;
            }
        }
        return false;
    }
    
}
