<?php

namespace OC\ChevalBundle\Repository;

/**
 * ChevalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChevalRepository extends \Doctrine\ORM\EntityRepository
{
}
