<?php

namespace OC\RationBundle\Repository;

/**
 * RationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RationRepository extends \Doctrine\ORM\EntityRepository
{
}
